name: digitalocean_deploy

on:
  push:
    branches: [main]
    
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main
      - name: Remove .env
        run: if [ -f .env]; then rm .env
      - name: Create .env
        run: echo 'PORT=${{secrets.PORT }}' > .env
        
      - name: Run build
        run: docker-compose up -d
